# version: "3.9"

services:
  docker_go:
    build: .
    container_name: container_go
    env_file: .env
    ports:
      - "8080:8080"

    environment:
      # - TZ=Europe/Kyiv
      #- MOCK_URL=http://mockserver:1080/participants
      - PARTICIPANTS_URL=http://localhost:8000/api/participants
      - SET_SECRET_URL=http://localhost:8000/new-word
